# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_parser')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_parser')
    _parser = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_parser', [dirname(__file__)])
        except ImportError:
            import _parser
            return _parser
        try:
            _mod = imp.load_module('_parser', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _parser = swig_import_helper()
    del swig_import_helper
else:
    import _parser
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _parser.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self) -> "PyObject *":
        return _parser.SwigPyIterator_value(self)

    def incr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _parser.SwigPyIterator_incr(self, n)

    def decr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _parser.SwigPyIterator_decr(self, n)

    def distance(self, x: 'SwigPyIterator') -> "ptrdiff_t":
        return _parser.SwigPyIterator_distance(self, x)

    def equal(self, x: 'SwigPyIterator') -> "bool":
        return _parser.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _parser.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _parser.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _parser.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _parser.SwigPyIterator_previous(self)

    def advance(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _parser.SwigPyIterator_advance(self, n)

    def __eq__(self, x: 'SwigPyIterator') -> "bool":
        return _parser.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: 'SwigPyIterator') -> "bool":
        return _parser.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _parser.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _parser.SwigPyIterator___isub__(self, n)

    def __add__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _parser.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _parser.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _parser.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Token(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Token, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Token, name)
    __repr__ = _swig_repr
    Type_Unknown = _parser.Token_Type_Unknown
    Type_Number = _parser.Token_Type_Number
    Type_Operator = _parser.Token_Type_Operator
    Type_LeftParen = _parser.Token_Type_LeftParen
    Type_RightParen = _parser.Token_Type_RightParen
    __swig_getmethods__["type"] = _parser.Token_type_get
    if _newclass:
        type = _swig_property(_parser.Token_type_get)
    __swig_getmethods__["str"] = _parser.Token_str_get
    if _newclass:
        str = _swig_property(_parser.Token_str_get)
    __swig_getmethods__["precedence"] = _parser.Token_precedence_get
    if _newclass:
        precedence = _swig_property(_parser.Token_precedence_get)
    __swig_getmethods__["rightAssociative"] = _parser.Token_rightAssociative_get
    if _newclass:
        rightAssociative = _swig_property(_parser.Token_rightAssociative_get)

    def __init__(self, t: 'Token::Type', s: 'string const &', prec: 'int'=-1, ra: 'bool'=False):
        this = _parser.new_Token(t, s, prec, ra)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _parser.delete_Token
    __del__ = lambda self: None
Token_swigregister = _parser.Token_swigregister
Token_swigregister(Token)


def expressToTokens(s: 'string const &') -> "deque< Token,std::allocator< Token > >":
    return _parser.expressToTokens(s)
expressToTokens = _parser.expressToTokens

def shutingYard(tokens: 'deque< Token,std::allocator< Token > > const &') -> "deque< Token,std::allocator< Token > >":
    return _parser.shutingYard(tokens)
shutingYard = _parser.shutingYard

def doCalculation(str: 'string const &') -> "float":
    return _parser.doCalculation(str)
doCalculation = _parser.doCalculation

def removeSpaces(str: 'string &') -> "void":
    return _parser.removeSpaces(str)
removeSpaces = _parser.removeSpaces
# This file is compatible with both classic and new-style classes.


